from analiseBasica import want33d
if __name__ == '__main__':
    dados = want33d()

print("=" * 40)
print("📊 want33d — Análise Técnica AERO/ETH")
print("=" * 40)
print(f"💰 Preço AERO: ${dados['preco_usd']}")
print(f"📈 Variações - 1h: {dados['variacao']['1h']}% | 6h: {dados['variacao']['6h']}% | 24h: {dados['variacao']['24h']}%")
print(f"📦 Volumes   - 1h: ${dados['volume']['1h']:,.2f} | 6h: ${dados['volume']['6h']:,.2f} | 24h: ${dados['volume']['24h']:,.2f}")
print(f"🛒 Transações *Buy|Sell* - 1h: ({dados['transacoes']['c1h']}, {dados['transacoes']['v1h']}) | 6h: ({dados['transacoes']['c6h']}, {dados['transacoes']['v6h']}) | 24h: ({dados['transacoes']['c24h']}, {dados['transacoes']['v24h']})")
print(f"🔁 Total Transações *Buy|Sell* - 1h: {dados['transacoesTotal']['t1h']} | 6h: {dados['transacoesTotal']['t6h']} | 24h: {dados['transacoesTotal']['t24h']}")
print(f'🟩 Força Compradora 24h: {dados['transacoes']['c24h'] / dados['transacoesTotal']['t24h']*100:.2f}%')
print(f'🟥 Força Vendedora 24h: {dados['transacoes']['v24h'] / dados['transacoesTotal']['t24h']*100:.2f}%')
print(f"🌊 Liquidez AERO/ETH: ${dados['liquidez_usd']:,.2f}")
print(f"🏦 MarketCap: ${dados['marketCap']:,.2f}")
print("=" * 40)
print("⚙️ Isso aqui não foi gerado por IA, foi suado mesmo 😅")
print("📢 Projeto pessoal do João Araújo — me segue lá no LinkedIn, vai que eu viro dev famoso: linkedin.com/in/joaoaraujo-dev")
print("=" * 40)
